version: "3"
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - WEBHOOK_URL=https://TU-URL-DE-RENDER.onrender.com
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
